#!/usr/bin/env python3

import argparse
import datetime
import re
import subprocess


def get_gpu_temperature():
    result = subprocess.check_output(["vcgencmd", "measure_temp"])
    match = re.search(r"([0-9\.]+)", result.decode("utf-8"))
    return float(match.group(0))


def get_cpu_temperature():
    with open("/sys/class/thermal/thermal_zone0/temp", "r") as fh:
        return float(fh.read()) / 1000


def main():
    parser = argparse.ArgumentParser(description="Output a summary of the Raspberry Pi's status.")
    options = parser.parse_args()

    cpu_temperature = get_cpu_temperature()
    gpu_temperature = get_gpu_temperature()
    print(",".join([str(datetime.datetime.now()), str(cpu_temperature), str(gpu_temperature)]))


if __name__ == "__main__":
    main()
